controllers:
    resource: ../src/Controller/
    exclude: ../src/Controller/Admin
    type: annotation
    
admin:
    resource: ../src/Controller/Admin
    type: annotation
    prefix: '/admin'

kernel:
    resource: ../src/Kernel.php
    type: annotation
